// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmqCf8ujYn0Io3MIYYOM4oGSwA3cVpleg',
    appId: '1:566622704497:web:11fd724c929995fcfedcd0',
    messagingSenderId: '566622704497',
    projectId: 'todo-testing-48609',
    authDomain: 'todo-testing-48609.firebaseapp.com',
    storageBucket: 'todo-testing-48609.appspot.com',
    measurementId: 'G-H0YJQHE4BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdRq9OPpk6O9L0NBZqwmMWwfRu1Bdb2k',
    appId: '1:566622704497:android:0dbfa57b7d248eb4fedcd0',
    messagingSenderId: '566622704497',
    projectId: 'todo-testing-48609',
    storageBucket: 'todo-testing-48609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3Sy5lITM0YeOy3BL2NiEVtDQn-1-KGo',
    appId: '1:566622704497:ios:7cce637c0f86bad3fedcd0',
    messagingSenderId: '566622704497',
    projectId: 'todo-testing-48609',
    storageBucket: 'todo-testing-48609.appspot.com',
    iosBundleId: 'com.example.todoFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh3Sy5lITM0YeOy3BL2NiEVtDQn-1-KGo',
    appId: '1:566622704497:ios:1d6c9bca25974407fedcd0',
    messagingSenderId: '566622704497',
    projectId: 'todo-testing-48609',
    storageBucket: 'todo-testing-48609.appspot.com',
    iosBundleId: 'com.example.todoFb.RunnerTests',
  );
}
